# A config file for traininig PWCNet

sintel:
  directory: '/Users/Daigo/Data/MPI-Sintel-complete'
  mode: 'clean'

preprocess:
  crop_size: [384, 448]

model:
  filters_list: [16, 32, 64, 96, 128, 192]
  leak_rate: 0.1
  max_displacement: 4
  name: 'pwcnet'

train:
  epochs: 10
  batch_size: 4
  gamma: 0.0004
  optimizer:
    learning_rate: 0.0001
    beta_1: 0.9
    beta_2: 0.999
  validation_split: 0.1

output_dir: '.'
